build:
  dependencies:
    before:
      - true
    override:
      - true
  tests:
    override:
      - true

tools:
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer: false
  php_cs_fixer: false
  php_loc: false
  php_cpd: false
  sensiolabs_security_checker: false

checks:
  php:
    code_rating: true
    duplication: true